CREATE TABLE PERIODS(
PERIOD_ID		INT PRIMARY KEY IDENTITY(1, 1),
PERIOD_YEAR		INT NOT NULL,
PERIOD_QUARTER  VARCHAR(2) NOT NULL,
PERIOD_LABEL	VARCHAR(10) NOT NULL UNIQUE
);

INSERT INTO PERIODS(PERIOD_YEAR,PERIOD_QUARTER,PERIOD_LABEL)
VALUES 
(2025, 'Q1', '2025Q1'), (2025, 'Q2', '2025Q2'), (2025, 'Q3', '2025Q3'), (2025, 'Q4', '2025Q4'), (2026, 'Q1', '2026Q1');

CREATE TABLE SECTORS(
SECTOR_ID	INT PRIMARY KEY IDENTITY(1, 1),
SECTOR_NAME NVARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO SECTORS(SECTOR_NAME)
VALUES 
('İmalat'),('Toptan ve Perakende Ticaret'),('Konaklama ve Yiyecek Hizmeti Faaliyetleri'),('Mesleki, Bilimsel ve Teknik Faaliyetler'),('İnşaat'),
('Diğer Hizmet Faaliyetleri'),('İdari ve Destek Hizmet Faaliyetleri'),('Ulaştırma ve Depolama'),('İnsan Sağlığı ve Sosyal Hizmet Faaliyetleri'),
('Bilgi ve İletişim'),('Eğitim'),('Finans ve Sigorta Faaliyetleri'),('Gayrimenkul Faaliyetleri'),('Kültür, Sanat Eğlence, Dinlence ve Spor'),
('Elektrik, Gaz, Buhar ve İklimlendirme Üretimi ve Dağıtımı'),('Madencilik ve Taş Ocakçılığı'),('Su Temini; Kanalizasyon, Atık Yönetimi ve İyileştirme Faaliyetleri');

CREATE TABLE EMPLOYMENT_EXPECTATIONS(
EXPECTATION_ID					INT PRIMARY KEY IDENTITY(1,1),
PERIOD_ID						INT NOT NULL,
SECTOR_ID						INT NOT NULL,
MAINTAIN_OR_INCREASE_PCT		DECIMAL(5,2) NOT NULL,
DECREASE_PCT					DECIMAL(5,2) NOT NULL,
NO_OPINION_PCT					DECIMAL(5,2) NOT NULL,
CONSTRAINT fk_employment_period
	FOREIGN KEY (PERIOD_ID) REFERENCES PERIODS(PERIOD_ID),
CONSTRAINT fk_employment_sector
	FOREIGN KEY (SECTOR_ID) REFERENCES SECTORS(SECTOR_ID),
CONSTRAINT fk_employment_period_sector
        UNIQUE (PERIOD_ID, SECTOR_ID)
);

INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,13,84.00, 2.90, 13.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,4,82.40, 3.30, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,14,81.90, 5.50, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,3,81.80, 5.60, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,11,80.00, 7.10, 12.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,6,80.00, 5.70, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,8,79.90, 5.50, 14.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,2,79.00, 6.60, 14.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,7,78.20, 5.00, 16.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,10,78.10, 6.00, 15.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,12,78.00, 6.20, 15.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,9,77.10, 5.30, 17.50);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,15,77.00, 3.30, 19.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,1,76.90, 7.60, 15.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,16,73.80, 5.30, 20.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,5,73.40, 6.00, 20.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(5,17,73.10, 7.10, 19.80);

INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,13,84.00, 2.90, 13.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,4,82.40, 3.30, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,14,81.90, 5.50, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,3,81.80, 5.60, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,11,80.00, 7.10, 12.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,6,80.00, 5.70, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,8,79.90, 5.50, 14.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,2,79.00, 6.60, 14.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,7,78.20, 5.00, 16.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,10,78.10, 6.00, 15.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,12,78.00, 6.20, 15.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,9,77.10, 5.30, 17.50);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,15,77.00, 3.30, 19.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,1,76.90, 7.60, 15.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,16,73.80, 5.30, 20.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,5,73.40, 6.00, 20.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(4,17,73.10, 7.10, 19.80);

INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,13,84.00, 2.90, 13.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,4,82.40, 3.30, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,14,81.90, 5.50, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,3,81.80, 5.60, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,11,80.00, 7.10, 12.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,6,80.00, 5.70, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,8,79.90, 5.50, 14.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,2,79.00, 6.60, 14.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,7,78.20, 5.00, 16.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,10,78.10, 6.00, 15.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,12,78.00, 6.20, 15.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,9,77.10, 5.30, 17.50);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,15,77.00, 3.30, 19.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,1,76.90, 7.60, 15.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,16,73.80, 5.30, 20.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,5,73.40, 6.00, 20.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(3,17,73.10, 7.10, 19.80);

INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,13,84.00, 2.90, 13.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,4,82.40, 3.30, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,14,81.90, 5.50, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,3,81.80, 5.60, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,11,80.00, 7.10, 12.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,6,80.00, 5.70, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,8,79.90, 5.50, 14.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,2,79.00, 6.60, 14.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,7,78.20, 5.00, 16.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,10,78.10, 6.00, 15.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,12,78.00, 6.20, 15.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,9,77.10, 5.30, 17.50);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,15,77.00, 3.30, 19.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,1,76.90, 7.60, 15.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,16,73.80, 5.30, 20.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,5,73.40, 6.00, 20.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(2,17,73.10, 7.10, 19.80);

INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,13,84.00, 2.90, 13.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,4,82.40, 3.30, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,14,81.90, 5.50, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,3,81.80, 5.60, 12.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,11,80.00, 7.10, 12.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,6,80.00, 5.70, 14.30);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,8,79.90, 5.50, 14.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,2,79.00, 6.60, 14.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,7,78.20, 5.00, 16.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,10,78.10, 6.00, 15.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,12,78.00, 6.20, 15.70);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,9,77.10, 5.30, 17.50);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,15,77.00, 3.30, 19.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,1,76.90, 7.60, 15.40);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,16,73.80, 5.30, 20.90);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,5,73.40, 6.00, 20.60);
INSERT INTO EMPLOYMENT_EXPECTATIONS(PERIOD_ID,SECTOR_ID,MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT) VALUES(1,17,73.10, 7.10, 19.80);

CREATE TABLE QUARTERLY_CORE_METRICS(
CORE_METRIC_ID         INT PRIMARY KEY IDENTITY(1,1),
PERIOD_ID               INT NOT NULL,
SECTOR_ID               INT NOT NULL,
EMPLOYEE_COUNT          INT NOT NULL,
OPEN_JOB_COUNT			INT NOT NULL,
OPEN_JOB_RATE_PCT		DECIMAL(5,2) NOT NULL,
OPEN_POSITION_PCT	DECIMAL(5,2) NOT NULL,
CONSTRAINT fk_quarterly_period
	FOREIGN KEY (PERIOD_ID) REFERENCES PERIODS(PERIOD_ID),
CONSTRAINT fk_quarterly_sector
	FOREIGN KEY (SECTOR_ID) REFERENCES SECTORS(SECTOR_ID),
CONSTRAINT pk_quarter_period_sector
        UNIQUE (PERIOD_ID, SECTOR_ID)
);

INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,1, 3589558, 81303, 2.20, 30.00 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,2, 4088180, 56402, 1.40, 20.80 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,3, 3311283, 53911, 1.60, 19.90);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,4, 1107366, 17351, 1.50, 6.40);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,5, 1618013, 14175, 0.90, 5.20);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,6, 367521, 10111, 2.70, 3.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,7, 1249641, 9219, 0.70, 3.40);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,8, 1421543, 8530, 0.60, 3.10 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,9, 629067, 5740, 0.90, 2.10 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,10, 342991, 3515, 1.00, 1.30);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,11 ,647866, 3101, 0.50, 1.10);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,12, 228161, 2121, 0.90, 0.80 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,13, 165612, 1997, 1.20, 0.70);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,14, 107165, 1105, 1.00, 0.40);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,15, 116519, 904, 0.80, 0.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,16, 109975, 875, 0.80, 0.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(5,17, 64153, 593, 0.90, 0.20 );

INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,1, 4477895, 31494, 0.70, 24.10 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,5, 2041961, 25528, 1.20, 19.60 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,2, 3352480, 22142, 0.70, 17.00 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,7, 2337517, 15335, 0.70, 11.80 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,3, 1271217, 14550, 1.10, 11.20 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,9, 609822, 4877, 0.80, 3.70);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,4, 817197, 4808, 0.60, 3.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,8, 1362423, 4467, 0.30, 3.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,10, 331124, 1431, 0.40, 1.10 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,6, 356522, 1184, 0.30, 0.90 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,12, 227011, 1098, 0.50, 0.80 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,14, 98076, 1024, 1.00, 0.80 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,11, 405204, 795, 0.20, 0.60);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,13, 173481, 603, 0.30, 0.50 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,16, 119057, 390, 0.30, 0.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,17, 65891, 362, 0.50, 0.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(4,15, 110298, 338, 0.30, 0.30 );

INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,1, 4564239, 50964, 1.10, 25.50);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,2, 3450667, 32406, 0.90, 16.20 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,7, 2505376, 26412, 1.00, 13.20 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,3, 1484794, 21166, 1.40, 10.60);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,5, 2027702, 20806, 1.00, 10.40);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,8, 1348715, 16423, 1.20, 8.20 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,4, 867127, 15899, 1.80, 7.90 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,9, 619972, 4532, 0.70, 2.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,11, 369677, 2897, 0.80, 1.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,6, 356201, 1988, 0.60, 1.00 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,12, 232834, 1942, 0.80, 1.00 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,10, 334850, 1328, 0.40, 0.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,14, 108222, 1056, 1.00, 0.50 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,16, 120723, 981, 0.80, 0.50 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,13, 175334, 587, 0.30, 0.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,15, 112848, 413, 0.40, 0.20 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(3,17, 66050, 384, 0.60, 0.20 );

INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,1, 4582077, 48868, 1.10, 23.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,2, 3452617, 37305, 1.10, 18.10);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,3, 1374270, 33268, 2.40, 16.10 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,7, 2207015, 25956, 1.20, 12.60 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,5, 1945009, 25952, 1.30, 12.60);
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,8, 1379578, 7842, 0.60, 3.80 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,4, 867593, 6861, 0.80, 3.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,9, 627798, 6767, 1.10, 3.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,6, 356834, 4058, 1.10, 2.00 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,11, 408390, 2120, 0.50, 1.00 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,12, 237708, 1451, 0.60, 0.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,10, 338154, 1423, 0.40, 0.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,15, 115842, 1410, 1.20, 0.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,13, 163385, 953, 0.60, 0.50 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,16, 122539, 900, 0.70, 0.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,14, 100163, 691, 0.70, 0.30 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(2,17, 66465, 364, 0.50, 0.20 );

INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,1, 4505367, 118588, 2.60, 34.50 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,2, 3597552, 66784, 1.80, 19.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,5, 2117573, 41996, 1.90, 12.20 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,7, 2588185, 32426, 1.20, 9.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,3, 1170921, 28873, 2.40, 8.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,8, 1434931, 15238, 1.10, 4.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,4, 884247, 9162, 1.00, 2.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,6, 369770, 7253, 1.90, 2.10 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,9, 665821, 6994, 1.00, 2.00 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,11, 463418, 3189, 0.70, 0.90 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,10, 352746, 3124, 0.90, 0.90 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,13, 166967, 2779, 1.60, 0.80 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,12, 236212, 2493, 1.00, 0.70 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,14, 94994, 1559, 1.60, 0.50 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,15, 127177, 1495, 1.20, 0.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,16, 116158, 1313, 1.10, 0.40 );
INSERT INTO QUARTERLY_CORE_METRICS(PERIOD_ID, SECTOR_ID, EMPLOYEE_COUNT, OPEN_JOB_COUNT, OPEN_JOB_RATE_PCT,OPEN_POSITION_PCT ) VALUES(1,17, 68639, 503, 0.70, 0.10 );

CREATE TABLE PRODUCTION_EXPECTATIONS(
PRODUCTION_EXPECTATION_ID		  INT PRIMARY KEY IDENTITY(1,1),
PERIOD_ID						  INT NOT NULL,
SECTOR_ID						  INT NOT NULL,
MAINTAIN_OR_INCREASE_PCT		  DECIMAL(5,2) NOT NULL,
DECREASE_PCT					  DECIMAL(5,2) NOT NULL,
NO_OPINION_PCT					  DECIMAL(5,2) NOT NULL,
CONSTRAINT fk_production_period
	FOREIGN KEY (PERIOD_ID) REFERENCES PERIODS(PERIOD_ID),
CONSTRAINT fk_production_sector
	FOREIGN KEY (SECTOR_ID) REFERENCES SECTORS(SECTOR_ID),
CONSTRAINT fk_production_period_sector
        UNIQUE (PERIOD_ID, SECTOR_ID)
);

INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,11, 78.40, 7.30, 14.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,3, 76.10, 9.00, 14.90);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,13, 75.60, 7.70, 16.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,4, 75.00, 6.20, 18.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,15, 74.40, 4.30, 21.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,12, 74.30, 6.70, 19.00);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,10, 73.80, 9.40, 16.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,6, 73.20, 9.20, 17.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,14, 73.00, 8.10, 18.90);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,7, 72.40, 10.10, 17.50);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,8, 72.00, 9.60, 18.40);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,1, 71.90, 10.70, 17.40);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,9, 71.10, 5.80, 23.00);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,2, 69.90, 12.80, 17.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,17, 68.90, 9.70, 21.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,16, 68.80, 6.70, 24.40);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(5,5, 68.10, 8.50, 23.40);

INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,10, 80.20, 4.20, 15.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,4, 79.20, 5.00, 15.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,9, 78.60, 3.80, 17.50);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,11, 78.10, 7.00, 14.90);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,14, 75.60, 8.60, 15.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,15, 75.10, 3.50, 21.40);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,12, 74.10, 5.80, 20.10);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,3, 72.00, 12.30, 15.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,6, 72.00, 10.10, 18.00);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,13, 71.60, 7.10, 21.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,7, 71.40, 10.00, 18.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,8, 71.10, 8.00, 20.90);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,2, 71.00, 10.30, 18.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,5, 70.50, 8.40, 21.10);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,1, 69.80, 9.90, 20.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,17, 64.90, 13.80, 21.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(4,16, 60.20, 13.00, 26.80);

INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,4, 80.60, 4.10, 15.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,9, 80.10, 3.90, 15.90);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,11, 77.60, 6.00, 16.40);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,12, 76.30, 7.20, 16.50);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,6, 75.40, 8.00, 16.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,14, 75.00, 9.30, 15.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,10, 73.90, 6.60, 19.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,15, 73.50, 3.90, 22.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,8, 72.90, 7.20, 19.90);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,3, 72.30, 11.70, 16.00);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,13, 71.50, 9.30, 19.20);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,2, 71.40, 10.10, 18.50);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,7, 69.60, 8.40, 22.00);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,5, 69.10, 9.10, 21.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,16, 67.80, 8.50, 23.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,1, 63.60, 11.30, 25.10);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(3,17, 62.00, 12.90, 25.20);

INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,10, 79.00, 4.70, 16.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,6, 77.50, 5.30, 17.20);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,4, 77.30, 5.20, 17.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,9, 77.20, 7.60, 15.20);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,12, 73.40, 7.80, 18.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,15, 73.00, 3.90, 23.10);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,3, 72.90, 8.20, 19.00);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,7, 72.50, 7.40, 20.10);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,8, 72.20, 6.70, 21.10);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,13, 71.80, 5.40, 22.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,16, 71.10, 5.70, 23.20);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,2, 70.80, 8.50, 20.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,11, 70.20, 11.00, 18.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,14, 69.70, 9.50, 20.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,1, 68.40, 8.30, 23.30);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,5, 67.90, 5.60, 26.50);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(2,17, 62.40, 11.60, 25.90);

INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,15, 79.70, 3.70, 16.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,12, 78.70, 5.10, 16.20);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,4, 77.10, 6.20, 16.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,10, 77.00, 4.80, 18.20);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,11, 74.70, 4.50, 20.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,6, 70.20, 11.10, 18.70);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,3, 69.30, 14.30, 16.40);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,7, 68.80, 8.40, 22.80);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,2, 68.40, 12.40, 19.20);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,16, 68.00, 10.60, 21.40);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,8, 67.60, 9.90, 22.50);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,5, 67.50, 9.10, 23.40);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,9, 67.50, 9.90, 22.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,13, 67.20, 8.70, 24.10);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,1, 65.60, 11.50, 22.90);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,14, 64.00, 12.30, 23.60);
INSERT INTO PRODUCTION_EXPECTATIONS(PERIOD_ID, SECTOR_ID, MAINTAIN_OR_INCREASE_PCT,DECREASE_PCT,NO_OPINION_PCT ) VALUES(1,17, 58.70, 16.00, 25.30);

CREATE TABLE OCCUPATION_SKILL_ANALYSIS(
SKILL_ANALYSIS_ID			 INT PRIMARY KEY IDENTITY(1,1),
PERIOD_ID					 INT NOT NULL, 
OCCUPATION_GROUP			 NVARCHAR(255) NOT NULL,
INDIVIDUAL_SKILL			 INT NOT NULL,
COMMUNICATION_SKILL			 INT NOT NULL,
PROBLEM_SOLVING_SKILL		 INT NOT NULL,
SOCIAL_SKILL				 INT NOT NULL,
TECHNICAL_SKILL				 INT NOT NULL,
CONSTRAINT fk_occupation_skill_period
	FOREIGN KEY (PERIOD_ID) REFERENCES PERIODS(PERIOD_ID)
);

INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Büro Hizmetlerinde Çalışan Elemanlar', 2, 3, 5, 1, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Hizmet ve Satış Elemanları', 4, 3, 2, 1, 5);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Nitelik Gerektirmeyen Meslekler', 1, 4, 3, 5, 2);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Nitelikli Tarım, Ormancılık ve Su Ürünleri Çalışanları', 1, 3, 5, 4, 2);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Profesyonel Meslek Mensupları', 4, 2, 1, 5, 3);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Sanatkârlar ve İlgili İşlerde Çalışanlar', 2, 4, 3, 5, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Teknisyenler, Teknikerler ve Yardımcı Profesyon el Meslek Mensupları', 1, 2, 3, 4, 5);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Tesis ve Makine Operatörleri ve Montajcılar', 5, 1, 2, 3, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(1, 'Yöneticiler', 3, 2, 1, 4, 5);

INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(2, 'Büro Hizmetlerinde Çalışan Elemanlar', 5, 4, 2, 3, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(2, 'Hizmet ve Satış Elemanları', 4, 2, 3, 1, 5);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(2, 'Nitelik Gerektirmeyen Meslekler', 1, 2, 3, 5, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(2, 'Nitelikli Tarım, Ormancılık ve Su Ürünleri Çalışanları', 2, 3, 4, 5, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(2, 'Profesyonel Meslek Mensupları', 5, 2, 4, 1, 3);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(2, 'Sanatkârlar ve İlgili İşlerde Çalışanlar', 3, 4, 1, 5, 2);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL, TECHNICAL_SKILL) VALUES(2, 'Teknisyenler, Teknikerler ve Yardımcı Profesyonel Meslek
Mensupları', 1, 2, 5, 3, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(2, 'Tesis ve Makine Operatörleri ve Montajcılar', 2, 3, 1, 5, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID, OCCUPATION_GROUP,INDIVIDUAL_SKILL, COMMUNICATION_SKILL, PROBLEM_SOLVING_SKILL, SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(2, 'Yöneticiler', 4, 3, 2, 1, 5);

INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Büro Hizmetlerinde Çalışan Elemanlar', 5, 2, 1, 4, 3);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Hizmet ve Satış Elemanları', 2, 1, 5, 3, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Nitelik Gerektirmeyen Meslekler', 1, 3, 4, 2, 5);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Nitelikli Tarım, Ormancılık ve Su Ürünleri Çalışanları', 3, 2, 1, 4, 5);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Profesyonel Meslek Mensupları', 5, 1, 2, 4, 3);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Sanatkârlar ve İlgili İşlerde Çalışanlar', 3, 5, 2, 4, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Teknisyenler, Teknikerler ve Yardımcı Profesyonel Meslek
Mensupları', 2, 1, 5, 3, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Tesis ve Makine Operatörleri ve Montajcılar', 4, 1, 5, 3, 2);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(3, 'Yöneticiler', 5, 2, 1, 4, 3);

INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Büro Hizmetlerinde Çalışan Elemanlar', 3, 1, 2, 5, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Hizmet ve Satış Elemanları', 1, 3, 2, 5, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Nitelik Gerektirmeyen Meslekler', 1, 3, 2, 4, 5);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Nitelikli Tarım, Ormancılık ve Su Ürünleri Çalışanları', 2, 4, 3, 5, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Profesyonel Meslek Mensupları', 3, 5, 2, 4, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Sanatkârlar ve İlgili İşlerde Çalışanlar', 1, 2, 4, 3, 5);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Teknisyenler, Teknikerler ve Yardımcı Profesyonel Meslek
Mensupları', 2, 1, 3, 5, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Tesis ve Makine Operatörleri ve Montajcılar', 2, 5, 3, 4, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(4, 'Yöneticiler', 2, 3, 1, 4, 5);

INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Büro Hizmetlerinde Çalışan Elemanlar', 4, 2, 3, 5, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Hizmet ve Satış Elemanları', 5, 1, 2, 3, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Nitelik Gerektirmeyen Meslekler', 1, 3, 2, 5, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Nitelikli Tarım, Ormancılık ve Su Ürünleri Çalışanları', 4, 1, 3, 2, 5);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Profesyonel Meslek Mensupları', 4, 2, 1, 5, 3);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Sanatkârlar ve İlgili İşlerde Çalışanlar', 3, 4, 2, 5, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Teknisyenler, Teknikerler ve Yardımcı Profesyonel
Meslek Mensupları', 5, 1, 2, 3, 4);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Tesis ve Makine Operatörleri ve Montajcılar', 3, 2, 4, 5, 1);
INSERT INTO OCCUPATION_SKILL_ANALYSIS(PERIOD_ID,OCCUPATION_GROUP,INDIVIDUAL_SKILL,COMMUNICATION_SKILL,PROBLEM_SOLVING_SKILL,SOCIAL_SKILL,TECHNICAL_SKILL) VALUES(5, 'Yöneticiler', 4, 3, 1, 5, 2);
