-- Her dönemde kaç sektör verisi bulunmaktadýr 
SELECT 
COUNT(DISTINCT S.SECTOR_ID) 
SECTOR_DISTINCT,
P.PERIOD_LABEL PERIOD_LABEL
FROM EMPLOYMENT_EXPECTATIONS E
JOIN PERIODS P ON E.PERIOD_ID = P.PERIOD_ID
JOIN SECTORS S ON E.SECTOR_ID = S.SECTOR_ID
WHERE P.PERIOD_LABEL IN  ('2025Q1', '2025Q2', '2025Q3', '2025Q4', '2026Q1')
GROUP BY P.PERIOD_LABEL
;

--Ayný dönem ve ayný sektör için tekrar eden kayýt var mý
SELECT  
S.SECTOR_NAME ,
P.PERIOD_LABEL,
COUNT(*) RECORD_COUNT
FROM EMPLOYMENT_EXPECTATIONS E
JOIN PERIODS P ON E.PERIOD_ID = P.PERIOD_ID
JOIN SECTORS S ON E.SECTOR_ID =S.SECTOR_ID
GROUP BY S.SECTOR_NAME, P.PERIOD_LABEL
HAVING COUNT(*) > 1;

--Her ana tabloda toplam kaç kayýt bulunmaktadýr
SELECT COUNT(*) COUNT_TOTAL
FROM PERIODS;

SELECT COUNT(*) COUNT_TOTAL
FROM SECTORS;

SELECT COUNT(*) COUNT_TOTAL
FROM EMPLOYMENT_EXPECTATIONS;

SELECT COUNT(*) COUNT_TOTAL
FROM PRODUCTION_EXPECTATIONS;

SELECT COUNT(*) COUNT_TOTAL
FROM QUARTERLY_CORE_METRICS;

SELECT COUNT(*) COUNT_TOTAL
FROM OCCUPATION_SKILL_ANALYSIS;

--2026Q1 döneminde en yüksek açýk iþ sayýsýna sahip ilk 10 sektör hangileridir
SELECT 
TOP 10
P.PERIOD_LABEL , 
S.SECTOR_NAME, 
Q.OPEN_JOB_COUNT
FROM QUARTERLY_CORE_METRICS Q
JOIN PERIODS P ON Q.PERIOD_ID = P.PERIOD_ID
JOIN SECTORS S ON Q.SECTOR_ID = S.SECTOR_ID
WHERE P.PERIOD_LABEL = '2026Q1'
ORDER BY Q.OPEN_JOB_COUNT DESC ;

--2025Q4 döneminde açýk iþ oraný en yüksek sektörler hangileridir
SELECT
P.PERIOD_LABEL, 
S.SECTOR_NAME,
Q.OPEN_JOB_RATE_PCT
FROM QUARTERLY_CORE_METRICS Q
JOIN PERIODS P ON Q.PERIOD_ID =P.PERIOD_ID
JOIN SECTORS S ON Q.SECTOR_ID = S.SECTOR_ID
WHERE P.PERIOD_LABEL = '2025Q4'
ORDER BY OPEN_JOB_RATE_PCT DESC

--Dönemlere göre toplam çalýþan sayýsý nasýl deðiþmiþtir
SELECT 
P.PERIOD_LABEL,
SUM(Q.EMPLOYEE_COUNT) [TOTAL NUMBER OF EMPLOYEES QUARTER]
FROM QUARTERLY_CORE_METRICS Q
JOIN PERIODS P ON Q.PERIOD_ID = P.PERIOD_ID
GROUP BY P.PERIOD_LABEL
ORDER BY P.PERIOD_LABEL DESC

--Dönemlere göre toplam açýk iþ sayýsý nasýl deðiþmiþtir
SELECT
P.PERIOD_LABEL,
SUM(Q.OPEN_JOB_COUNT) OPEN_JOB_TOTAL
FROM QUARTERLY_CORE_METRICS Q
JOIN PERIODS P ON Q.PERIOD_ID = P.PERIOD_ID
GROUP BY P.PERIOD_LABEL
ORDER BY P.PERIOD_LABEL 


--2025Q1 döneminde istihdamý artýrma/koruma beklentisi en yüksek sektörler hangileridir
SELECT 
P.PERIOD_LABEL,
S.SECTOR_NAME,
E.MAINTAIN_OR_INCREASE_PCT TOP_SECTORS
FROM EMPLOYMENT_EXPECTATIONS E
JOIN PERIODS P ON E.PERIOD_ID = P.PERIOD_ID
JOIN SECTORS S ON E.SECTOR_ID = S.SECTOR_ID
WHERE P.PERIOD_LABEL = '2025Q1'
ORDER BY TOP_SECTORS DESC;

--2025Q2 döneminde istihdam azaltma beklentisi en yüksek sektörler hangileridir
SELECT 
P.PERIOD_LABEL,
S.SECTOR_NAME,
E.DECREASE_PCT
FROM EMPLOYMENT_EXPECTATIONS E
JOIN PERIODS P ON E.PERIOD_ID = P.PERIOD_ID
JOIN SECTORS S ON E.SECTOR_ID = S.SECTOR_ID
WHERE P.PERIOD_LABEL = '2025Q2'
ORDER BY E.DECREASE_PCT DESC;

--2025Q3 döneminde üretim/hizmet artýþ beklentisi en yüksek sektörler hangileridir?
SELECT 
P.PERIOD_LABEL,
PE.MAINTAIN_OR_INCREASE_PCT,
S.SECTOR_NAME
FROM PRODUCTION_EXPECTATIONS PE
JOIN PERIODS P ON PE.PERIOD_ID = P.PERIOD_ID
JOIN SECTORS S ON PE.SECTOR_ID = S.SECTOR_ID
WHERE P.PERIOD_LABEL= '2025Q3'
ORDER BY PE.MAINTAIN_OR_INCREASE_PCT DESC;

--Ýstihdam beklentisi ile üretim beklentisi arasýndaki fark en yüksek olan sektörler hangileridir?
SELECT
S.SECTOR_NAME,
P.PERIOD_LABEL,
E.MAINTAIN_OR_INCREASE_PCT EMPLOYMENT_EXPECTATION,
PE.MAINTAIN_OR_INCREASE_PCT PRODUCTION_EXPECTATION,
ABS(E.MAINTAIN_OR_INCREASE_PCT - PE.MAINTAIN_OR_INCREASE_PCT) EXPECTATION_DIFFERENCE
FROM EMPLOYMENT_EXPECTATIONS E
JOIN PRODUCTION_EXPECTATIONS PE ON E.PERIOD_ID = PE.PERIOD_ID
AND E.SECTOR_ID = PE.SECTOR_ID
JOIN PERIODS P ON E.PERIOD_ID = P.PERIOD_ID
JOIN SECTORS S ON E.SECTOR_ID =S.SECTOR_ID
ORDER BY EXPECTATION_DIFFERENCE DESC

-- Meslek gruplarýna göre en yüksek teknik beceri, iletiþim becerisi ve problem çözme becerisi skorlarý hangileridir
SELECT 
LTRIM(RTRIM(O.OCCUPATION_GROUP)) AS OCCUPATION_GROUP,
AVG(CAST(O.TECHNICAL_SKILL AS DECIMAL(5,2)))  AVG_TECHNICAL_SKILL,
AVG(CAST(O.COMMUNICATION_SKILL AS DECIMAL(5,2)))  AVG_COMMUNICATION_SKILL,
AVG(CAST(O.PROBLEM_SOLVING_SKILL AS DECIMAL(5,2))) AVG_PROBLEM_SOLVING_SKILL
FROM OCCUPATION_SKILL_ANALYSIS O
GROUP BY LTRIM(RTRIM(O.OCCUPATION_GROUP))
ORDER BY AVG_PROBLEM_SOLVING_SKILL DESC;







